def printRules():
    print("---------------")
    print("Your party is fighting a evil Sorcerer...")
    print("Defeat his hoard or orcs to win!")
    print("You can choose your difficulty, the default is Easy:")
    print("Easy: waves of 4 orcs with default stats")
    print("Medium: waves of 4 orcs with enhanced stats")
    print("Hard: waves of 6 orcs with enhanced stats")
    print("The default number of waves is 1, but you can choose how many waves you want before starting the first round!")
    print("---------------")